CHANGELOG.md, fortls/constants.py, fortls/helper_functions.py, fortls/langserver.py, fortls/parse_fortran.py, fortls/regex_patterns.py, test/test_server.py, test/test_source/diag/test_scope_end_name_var.f90
Reorganises some of the files to make it easier to navigate. Ideally these methods and classes should all be put in smaller files but I would have to spend a substantial amount of time untangling them, which I do not have.
Also, Fixes #9
=> Split files

.github/workflows/main.yml, .gitignore, CHANGELOG.md, LICENSE, README.md, docs/conf.py, docs/fortls.rst, docs/index.rst, docs/options.rst, docs/requirements.txt, fortls/__init__.py, fortls/helper_functions.py, fortls/interface.py, fortls/langserver.py, fortls/parse_fortran.py, fortls/regex_patterns.py, test/test_interface.py, test/test_server.py, test/test_source/diag/test_forall.f90, test/test_source/excldir/sub1/tmp.f90, test/test_source/f90_config.json, test/test_source/hover/pointers.f90
- Updates documentation
- Updates LICENSE
- Updates .gitignore
- Adds field in documentation about all the changes (extracted from the changelog) between this project and fortran-language-server.
- Unifies the interface between command line arguments and configuration file interface
- Deprecates `preserve_keyword_order`
=> Unify command line and configure file interfaces

.github/workflows/python-publish.yml, CHANGELOG.md
Allows for the fortls version to be extracted from the release tag, substituted in place for the PyPi release and also committed to the dev branch and also the tag used for the release (force pushed).
Additionally, it signs the commits and the tags with a GPG key
=> Automates the commit of version numbers

fortls/objects.py
Remove extra curly brackets introduced in a82f4e2
Fixes #39
The existing tests don't capture this. I had a look at adding one:
```python
def test_procedure_completion():
def comp_request(file_path, line, char):
return write_rpc_request(
1,
"textDocument/completion",
{
"textDocument": {"uri": str(file_path)},
"position": {"line": line, "character": char},
},
)
string = write_rpc_request(1, "initialize", {"rootPath": str(test_dir)})
file_path = test_dir / "test_prog.f08"
string += comp_request(file_path, 26, 17)
errcode, results = run_request(string)
assert errcode == 0
exp_results = (
{
"label": "test_sig_Sub",
"insertText": "test_sig_Sub(${1:arg1}, ${2:arg2}, opt1=${3:opt1}, opt2=${4:opt2}, opt3=${5:opt3})",
},
)
print(results[1])
for expected_result, result in zip(exp_results, …
```
=> Fix text completion for procedures

fortls/intrinsics.py
By default python in Windows in zh_CN will use GBK to open files, since we're using UTF-8 now, it will throw error like this:
```
Traceback (most recent call last):
File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\Program Files\Python310\Scripts\fortls.exe\__main__.py", line 7, in <module>
File "C:\Program Files\Python310\lib\site-packages\fortls\__init__.py", line 56, in main
LangServer(
File "C:\Program Files\Python310\lib\site-packages\fortls\langserver.py", line 119, in __init__
) = load_intrinsics()
File "C:\Program Files\Python310\lib\site-packages\fortls\intrinsics.py", line 168, in load_intrinsics …
```
=> Fix error in Windows in zh_CN locale

CHANGELOG.md, fortls/regex_patterns.py, test/test_preproc.py, test/test_source/pp/include/petscerror.h, test/test_source/pp/preproc.F90
The regex that checks for preprocessor macros using the 'defined'
operator assumes that the macro that follows the operator is between
parenthesis. However, the syntax for the 'defined' operator does not
require parenthesis, at least in GNU Cpp [1] and Intel fpp [2], arguably
the two most commonly used Fortran preprocessors.
Tweak the regex by allowing the opening and closing parenthesis zero or
once.
[1] https://gcc.gnu.org/onlinedocs/gcc-10.2.0/cpp/Defined.html#Defined
[2] https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/optimization-and-programming-guide/fpp-preprocessing/using-fpp-preprocessor-directives.html
=> Do not require parentheses for the `defined` preprocessor operator

CHANGELOG.md, fortls/interface.py, fortls/langserver.py, test/test_interface.py, test/test_server.py
Removes hooks for `--variable_hover`, now always enabled
=> Deprecated `--variable_hover`

docs/editor_integration.rst
=> add kakoune editor

CHANGELOG.md, fortls/langserver.py
This should prevent `fortls` from fetching dev and pre-release versions
=> Disable PyPi autoupdate for prereleases and dev

CHANGELOG.md, fortls/langserver.py, test/test_server_implementation.py
Closes Request textDocument/implementation failed. #80
=> Fixes GoTo Implementation for intrinsics

CHANGELOG.md, fortls/intrinsics.py, fortls/keywords.json, fortls/statements.json, test/test_server.py
acc. to. Intel oneAPI Develeoper (p. 2246) for consistency. I left out the vendor specific keywords `AUTOMATIC` and  `STATIC`. 
Probably it is better to switch to a not vendor specific document for refernce for example `ISO_1539-1_Fortran_Standart_2018`
=> extended list of keywords

CHANGELOG.md, fortls/langserver.py, test/test_interface.py
=> Coverage report PR failure

CHANGELOG.md, fortls/__init__.py, fortls/ftypes.py, fortls/intrinsics.py, fortls/langserver.py, fortls/objects.py, fortls/parse_fortran.py, test/test_server_diagnostics.py, test/test_source/diag/test_contains.f90, test/test_source/diag/test_function.f90, test/test_source/diag/test_import.f90, test/test_source/diag/test_variable.f90, test/test_source/diag/test_visibility.f90
=> Rename Fortran classes used for AST

CHANGELOG.md, README.md, fortls/langserver.py
Fixes Feature request:  documentHighlightProvider support #43
=> Added `textDocument/documentHighlight`

fortls/regex_patterns.py
=> chore: Update Fortran regex

CHANGELOG.md, fortls/interface.py, fortls/langserver.py, test/test_interface.py
=> Resolve glob errors in cmd

docs/editor_integration.rst
eglot is a popular lsp client for emacs that supports fortls.
=> mention eglot for emacs support

CHANGELOG.md, CITATION.cff
TODO: missing doi and Zenodo badge
=> feat: added basic citation file

fortls.py, fortls/__main__.py, test/setup_tests.py
Add a `__main__.py` to allow running `python -m fortls`.
=> Allow running python -m fortls

CHANGELOG.md, fortls/helper_functions.py, fortls/intrinsics.py, fortls/langserver.py, fortls/objects.py, test/test_server_completion.py, test/test_server_hover.py
=> feat: Change autocomplete to use MarkupContent

.coveragerc, .github/workflows/main.yml, .github/workflows/python-publish.yml, CHANGELOG.md, fortls/__init__.py, fortls/fortls.schema.json, fortls/interface.py, fortls/schema.py, setup.cfg
Adds a JSON schema validator for the configuration options offered. The schema is autogenerated via the CLI.
It also changes how the version display happens.
Fixes #204
=> feat: add JSON schema for fortls configuration

README.md, docs/quickstart.rst
=> docs: replace wording binary with executable

CHANGELOG.md, fortls/langserver.py, fortls/objects.py, fortls/parse_fortran.py, test/test_parser.py, test/test_source/parse/submodule.f90
The submodule AST node was setting the name of the
object to None instead of an empty string which caused
havoc in all sorts of places.
Fixes #233
=> bug: incomplete submodule setting name to None

.coveragerc, CHANGELOG.md, fortls/ftypes.py, fortls/objects.py, fortls/parse_fortran.py, fortls/regex_patterns.py, pyproject.toml, setup.cfg, test/test_server_completion.py, test/test_server_diagnostics.py, test/test_source/diag/test_var_shadowing_keyword_arg.f90
Preliminary work on parsing attributes such as kind, len
as separate variables in the AST node.
They can then be excluded from the dublication check
for diagnostics.
Fixes #173
Fixes #175
=> fix: len and kind attribute mistaken as variables

CHANGELOG.md, fortls/langserver.py, fortls/objects.py, test/test_server_documentation.py, test/test_server_hover.py, test/test_source/docs/test_module_and_type_doc.f90, test/test_source/hover/types.f90
=> feat: add hover for types and modules

CHANGELOG.md, fortls/regex_patterns.py, test/test_server_diagnostics.py, test/test_source/diag/test_critical.f90
=> bug: fixes `CRITICAL` "Unexpected end of scope"

CHANGELOG.md, fortls/objects.py, fortls/parse_fortran.py, test/test_server_hover.py, test/test_source/hover/associate_block_2.f90
I think the signature is still not ideal
i.e. `LOGICAL FUNCTION` but I chose it
since it indicates that the associate block
variable is the result of a function.
Fixes #269
=> fix: associate block from Function result

README.md, docs/features.rst
In the readme and the doc, `IOS_C_BINDING` was written instead of instead of `ISO_C_BINDING`.
=> Fix small typo

fortls/regex_patterns.py, test/test_server_hover.py, test/test_source/hover/parameters.f90
Modify regex of parameter's values. Add division sign, allow spaces in values of parameters. Extend unittests with parameters variables. 
@gnikit
=> Issue #284 fix and extend hover of parameters.

fortls/langserver.py
Passing `--incl_suffix` to fortls as command line arguments did not take any effect. Although the arguments were parsed correctly and set as attributes to the `LangServer` instance, they where never passed to `src_file_exts` and hence got ignored later when iterating the root directory.
This is especially problematic when fortls is used via the Modern Fortran VS code extension when it tries to pass along settings from the `settings.json` file.
=> Fix passing `incl_suffixes` as command line arguments to fortls

CHANGELOG.md, docs/options.rst, fortls/fortls.schema.json, fortls/interface.py, fortls/langserver.py, fortls/regex_patterns.py, setup.cfg, test/test_regex_patterns.py
The regex now allows for more failthul patterns to the input strings
to be formed.
In the future we should probably allow full regex expressions as inputs,
as opposed to now, where we escape special characters.
Fixes #300
=> fix: rewrote the source file extension REGEX

CHANGELOG.md, fortls/langserver.py, fortls/objects.py, test/test_server_implementation.py, test/test_source/imp/submodule.f90
It is now possible for interfaces with implementations in submodules i.e. a Function or a Subroutine
Fixes #74
=> fix: Go To Implementation works for submodules

fortls/helper_functions.py, fortls/intrinsics.py, fortls/json_templates.py, fortls/objects.py
This is meant as a first step to separating concerns and refactoring the codebase so as to receive AST nodes from LFortran.
=> Refactoring Fortran Objects

test/test_interface.py
Previously, the unit test `test_version_update_pypi()` was not correctly loading the server configuration.  The test was passing simply because the first assertion assumed a configuration was used that happened to match the default configuration.  If the configuration of `f90_config.json` were to be changed in a way that should affect the test, the test would have failed.
The unit test is updated to match the paradigm of the other unit tests in this file, deferring the server init to `unittest_server_init()`, which does correctly load the configuration.
Furthermore, if the unit tests are run in a conda environment, the test was erroneously failing.  In such an environment, the expected outcome should be different than the one assumed by the CI.  In order to satisfy both, the unit test now …
=> Fix version update unit test

fortls/parsers/internal/parser.py, fortls/regex_patterns.py, test/test_server_hover.py, test/test_source/hover/parameters.f90
Some language dialects allow dollar signs in symbol names.  In Intel, this is always allowed.  In g77, it can be enabled via [command line flag](https://gcc.gnu.org/onlinedocs/gcc-2.95.3/g77_13.html#SEC380).  This seems to be an older practice that has fallen out of favor and was always a language extension, but is needed to support backward compatibility with older codes.
I've opted to implement this as always allowed like the Intel implementation, but I can change this to be an opt-in feature if we'd rather.  I don't suspect it will hurt anyone to allow it.  
There are other noted historical uses of `$` in Fortran that are more rare, particularly with different variations of write statements, but it is unclear if any of these are still supported today by any compilers. (Even if they …
=> Allow dollar in symbol names

CONTRIBUTING.md
Addresses compatibility issues with the shell script, making it work on zsh as well. Previously, the script was failing on zsh as square brackets are used for pattern matching in zsh. By adding double quotes, the script now functions correctly across different shell environments.
> pip install -e ".[dev,docs]"
=> Addressing compatibility issue for shell script in CONTRIBUTING.md

.github/workflows/update-intrinsics.yml, fortls/parsers/internal/intrinsics.py
This fixes update instrinsics action #358  after updating the file paths according to new architecture. Tested the workflow by manually triggering it,works fine.
=> Fixes update intrinsics action

CHANGELOG.md, docs/options.rst, fortls/fortls.schema.json, fortls/interface.py, fortls/langserver.py, test/test_interface.py, test/test_source/f90_config.json
=> feat: add option to increase the default Python recursion depth

pyproject.toml
This removes ambiguity with submodules
=> build: update setuptools include pattern in pyproject.toml

CHANGELOG.md, fortls/parsers/internal/ast.py
=> chore: Fix parent scope issue in FortranAST class

CHANGELOG.md, fortls/parsers/internal/parser.py, test/test_parser.py, test/test_source/.fortls, test/test_source/parse/.fortls, test/test_source/parse/mixed/multilines.F90, test/test_source/parse/mixed/preproc_and_normal_syntax.F90
The logical operator `&&` present in the preprocessor
expressions interfered with the line continuation operator
`&` thus resulting into invalid syntax
Fixed #398
=> fix(parser): preproc operator mixed with line cont

CHANGELOG.md, fortls/helper_functions.py, test/test_server_hover.py, test/test_source/hover/complicated_kind_spec.f90
=> fix: properly locates closing parenthesis in the presence of quotes

CHANGELOG.md, fortls/parsers/internal/parser.py, test/test_server_hover.py, test/test_source/hover/multiline_lexical_tokens.f90
The support is more permissive than the standard dictates
and obviously does not comform with all the LSP responses
e.g. completions under certain conditions.
Fixes #235
=> fix(parser): support free-form line continuation in lexical tokens

fortls/parsers/internal/parser.py, test/test_preproc.py, test/test_source/pp/preproc_if_nested.F90
In the pre-processor code, when we check whether a `#define` or `#include` statement should be evaluated, only the top of the pre-processor stack was taken into account. This commit changes it so that *all* the previously taken branches need to evaluate to `true`.
Fixes #404.
=> Fix nested pre-processor blocks

CHANGELOG.md, fortls/langserver.py
=> fix(lsp): use correct symbol for submodules

CHANGELOG.md, fortls/parsers/internal/parser.py, test/test_server_references.py, test/test_source/fixed/comment_as_reference.f
This is the suggested fix for https://github.com/fortran-lang/fortls/issues/447. Please see https://github.com/fortran-lang/fortls/issues/447 for the exact description about what this fix is trying to address.
As pointed out in the issue above, it looks like a simple mistake in the condition for stripping comments. It works fine as below just by flipping the condition about the OpenMP instruction.
=> fix: flip the condition in strip_comment for fixed format

CHANGELOG.md, fortls/parsers/internal/parser.py
This is the suggested fix for issue #443. Please see it for the exact description about what this fix is trying to address.
The issue is caused by splitting the code into lines using `str.splitlines` built-in function, which has a different set of line separators than the editors. (See https://docs.python.org/3/library/stdtypes.html#str.splitlines ) This fix is using our own `splitlines` function instead to make the line separation rule more consistent with the editors.
Now fortls can return the correct information regardless of the form feed characters in the code.
=> fix: not treat form feed as line break (#443)

fortls/langserver.py, test/test_server_init.py
This is the suggested fix for #445. Please see #445 for the exact description about what this fix is trying to address.
The issue can be addressed by catching the errors raised from `result.get()` (receivning the result from the child process) in `LangServer.workspace_init`. The caught error can be convereted to string so that it will be posted as an error message.
With this fix, the fortls reports an "Initialization failed" message for the file that caused the RecusrionError, and successfully completes the initialization instead of crashing itself. It looks like below in VSCode (The red underline indicates the file that caused the issue).
=> fix: catch RecursionError in initialization

fortls/parsers/internal/subroutine.py, test/test_server_diagnostics.py, test/test_source/diag/test_mixed_case_interface_sub_child.f90
This commit fixes a bug where the sub children of an
interface would not be properly checked for their letter case.
Fixes #471
=> fix: diagnostic error for interface arguments

fortls/parsers/internal/parser.py, test/test_server_references.py, test/test_source/use/comment_after_use.f90
=> fix: find reference in USE after comment
